---
# tasks file for roles
- name: Updating OS Kernel
  ansible.builtin.iclude_tasks:      
    file: centos.yml 
  when: (ansible_facts['os_family'] == "Centos")

- name: Update ubuntu Kernel
  ansible.builtin.iclude_tasks:
    file: ubuntu.yml
  when: (ansible_facts['os_family'] == "Ubuntu" or ansible_facts['os_family'] == "Debian")

